### PR TITLE
Fix copy on linux

### LINKED ISSUE #131: Root backup command is ill formed
### Operating System

Pop!_OS 22.04 LTS

### VSCode Version

1.76.2

### Extension Version

v2.5.2

### Issue

This is a follow up to #118 

The admin prompt works now, however the command is ill formed on Linux:
`--: command not found`
Screenshot from 2023-03-30 00-09-56

Appears to be [the following line](https://github.com/KatsuteDev/Background/blob/main/src/extension.ts#L75)
``-- sh -c "cp -f '${workbench}' '${workbench_backup}'; cp -f '${product}' '${product_backup}'"``

### How to replicate

Accept the admin prompt on Linux

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*Issues must meet the following criteria:*

 - [x] No similar pull request exists.
 - [x] Code follows the general code style of this project.
 - [x] No sensitive information is exposed.
 - [x] Relevant comments have been added.

### Code Generators
*The use of GitHub Copilot or ChatGPT is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot or ChatGPT.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Closes #131
 - Simplified all to `&&` only, sudo executes a file so `&&` is sufficient

### Windows `win32`

Uses:

https://github.com/bpasero/sudo-prompt/blob/21d9308edcf970f0a9ee0580c539b1457b3dc45b/index.js#L631

```js
script.push(instance.command);
```

**No changes needed**

### Linux `linux`

Uses:

https://github.com/bpasero/sudo-prompt/blob/21d9308edcf970f0a9ee0580c539b1457b3dc45b/index.js#L153-L157

```js
command.push(
  '/bin/bash -c "echo ' + EscapeDoubleQuotes(magic.trim()) + '; ' +
  EscapeDoubleQuotes(instance.command) +
  '"'
);
```

**Redundant `/bin/bash -c "-- sh -c '...'"`**

### Mac `darwin`

Uses:

https://github.com/bpasero/sudo-prompt/blob/21d9308edcf970f0a9ee0580c539b1457b3dc45b/index.js#L315

```js
script.push(instance.command);
```

**No changes needed**

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -140,13 +153,12 @@ export const write: (content: string) => void = (content: string) => {
                 const jnt = tmp.fileSync().name;
                 fs.writeFileSync(jnt, fs.readFileSync(json, "utf-8").replace(replace, checksum).trim(), "utf-8");
 
-                const cmd: string = win
-                    ? `xcopy /r /y "${jst}" "${js}" && xcopy /r /y "${jnt}" "${json}"` // do not use *, xcopy defect
-                    : `-- sh -c "cp -f '${jst}' '${js}'; cp -f '${jnt}' '${json}'"`;
-
+                const cmd: string = cp([[jst, js], [jnt, json]], true);
```
Comment (Katsute) [inline src/extension.ts:156]: ✔️

**Comment by Katsute** [comment]
@mashiro-san approve
