### PR TITLE
Fix backup write not prompting for admin permission

### LINKED ISSUE #118: Fails on Linux with EACCES: permission denied, copyfile
### Operating System

Pop!_OS 22.04 LTS

### VSCode Version

1.76.1 (Sandboxed: No)

### Extension Version

v2.5.1

### Issue

My configuration works on Mac but fails on PopOS with the following error

```
2023-03-10 23:54:50.487 [error] Activating extension Katsute.code-background failed due to an error:
2023-03-10 23:54:50.487 [error] Error: EACCES: permission denied, copyfile '/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js' -> '/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main-backup.js'
	at Object.copyFileSync (node:fs:2804:3)
	at Object.func (node:electron/js2c/asar_bundle:5:1812)
	at activate (/home/robinfriedli/.vscode/extensions/katsute.code-background-2.5.1/dist/extension.js:53:24)
	at Ui.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14833)
	at Ui.cb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14532)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:12550
	at async f.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
	at async f.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
	at async f.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)
```

Not sure if this is related to #92

### How to replicate

Try to activate extension on PopOS or quite probably other distros

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*Issues must meet the following criteria:*

 - [x] No similar pull request exists.
 - [x] Code follows the general code style of this project.
 - [x] No sensitive information is exposed.
 - [x] Relevant comments have been added.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Fixes #118
 - Prompt for admin on backup write
 - Adjust messages
 - Apply `*` `xcopy` defect fix

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -126,15 +133,15 @@ export const write: (content: string) => void = (content: string) => {
...
-        vscode.window.showWarningMessage("Failed to write changes, run command as administrator?", {detail: `VSCode does not have permission to write to the VSCode folder, run command using administrator permissions?\n\n${err.message}`, modal: true}, "Yes").then((value?: string) => {
+        vscode.window.showWarningMessage("Failed to write changes, run command as administrator?", {detail: `The Background extension does not have permission to write changes, run command using administrator permissions?\n\n${err.message}`, modal: true}, "Yes").then((value?: string) => {
             if(value === "Yes"){
                 const jst = tmp.fileSync().name;
                 fs.writeFileSync(jst, content, "utf-8");
                 const jnt = tmp.fileSync().name;
                 fs.writeFileSync(jnt, fs.readFileSync(json, "utf-8").replace(replace, checksum).trim(), "utf-8");
 
                 const cmd: string = win
-                    ? `xcopy /r /y "${jst}" "${js}" && xcopy /r /y "${jnt}" "${json}"`
```
Comment (Katsute) [inline src/extension.ts:137]: Still functions properly, do not apply `*` to path.

**Comment by Katsute** [comment]
@mashiro-san approve
